/* This file is always linked into Core.  This allows Core to be installed as a standalone
   library, e.g. for use in a toplevel.  Our OMakeroot, when building an executable, uses
   ld --wrap to override these functions with the generated ones as autogenerated in
   *.build_info.c and *.hg_version.c. */


#include <caml/mlvalues.h>
#include <caml/memory.h>
#include <caml/alloc.h>

CAMLprim value generated_hg_version (value unit __attribute__ ((unused)))
{
  char v[] = "NO_VERSION_UTIL";
  return(caml_copy_string(v));
}

CAMLprim value generated_build_info (value unit __attribute__ ((unused)))
{
  char v[] = "("
      "(username \"\")"
      "(hostname \"\")"
      "(kernel   \"\")"
      "(build_date \"1970-01-01\")"
      "(build_time \"00:00:00\")"
      "(x_library_inlining false)"
      "(nodynlink true)"
      "(ocaml_version \"\")"
      "(executable_path \"\")"
      "(build_system \"\")"
      "(packing false)"
    ")";
  return(caml_copy_string(v));
}
