(** Disallows the empty string and whitespace around the edges in [of_string] and
    [t_of_sexp], but doesn't check when reading from bin_io. *)

open! Import

[%%template
module type Stringable = Stringable.S
module type%template [@mode local] Stringable = Stringable.S [@alloc stack]]

module type%template
  [@mode m = (global, local)] [@modality p = (portable, nonportable)] S_abstract = sig
  type t
  [@@deriving
    (bin_io [@mode m])
    , compare ~localize
    , equal ~localize
    , globalize
    , hash
    , sexp_grammar
    , sexp_of ~stackify]

  include Identifiable.S [@mode m] [@modality p] with type t := t
  include Stringable [@mode m] with type t := t
  include Quickcheckable.S with type t := t
  include Diffable.S_atomic with type t := t

  val arg_type : t Command.Arg_type.t

  module Stable : sig
    module V1 : sig
      type nonrec t = t
      [@@deriving
        (bin_io [@mode m])
        , compare ~localize
        , equal ~localize
        , globalize
        , hash
        , sexp_grammar
        , sexp_of ~stackify
        , stable_witness]

      include Stringable [@mode m] with type t := t

      include
        Stable_comparable.With_stable_witness.V1
        [@mode m]
        with type t := t
        with type comparator_witness = comparator_witness

      include Hashable.Stable.V1.With_stable_witness.S with type key := t
      include Diffable.S_atomic with type t := t
    end
  end
end

module type%template
  [@mode m = (global, local)] [@modality p = (portable, nonportable)] S =
  S_abstract [@mode m] [@modality p] with type t = private string

(** Some extra features we provide in [make], but don't want to require of any
    string-ID-like type. *)
module type%template
  [@mode m = (global, local)] [@modality p = (portable, nonportable)] S_with_extras = sig
  type t = private string [@@deriving typerep]

  include S [@mode m] [@modality p] with type t := t
end

module type%template String_id = sig
  include sig
    [@@@mode.default m = (global, local)]
    [@@@modality.default p = (portable, nonportable)]

    module type S = S [@mode m] [@modality p]
    module type S_abstract = S_abstract [@mode m] [@modality p]
    module type S_with_extras = S_with_extras [@mode m] [@modality p]
  end

  include S [@mode local] [@modality portable]

  module String_without_validation_without_pretty_printer :
    S_with_extras [@mode local] [@modality portable] with type t = string

  (** [make] customizes the error messages generated by [of_string]/[of_sexp] to include
      [module_name].

      The resulting [quickcheck_generator] generates non-empty strings containing only
      printable characters, and no whitespace at the edges. [quickcheck_generator] is
      dependent on [validate] (see [validate]'s doc-comment). *)
  val%template make
    :  ?validate:(string -> unit Or_error.t)
         (** Defaults to [const (Ok ())].

             Passing [validate] modifies [of_string]/[of_sexp]/[bin_read_t] to raise if
             [validate] returns an error, and modifies [quickcheck_generator] to use a
             naive [Generator.filter] to satisfy the validate constraint.

             For complex validation predicates, the generator may spin indefinitely trying
             to generate a satisfying string. In these cases, the client should shadow
             [quickcheck_generator] to construct valid strings directly. *)
    -> ?caller_identity:Bin_prot.Shape.Uuid.t
         (** Defaults to bin_shape of [String].

             The result of applying [make] without [caller_identity] is that it will have
             the same [Bin_prot.Shape]. This is usually not what you want, and it's
             recommended to use [caller_identity] to provide different shapes for
             different identifier types. *)
    -> ?include_pretty_printer:bool
         (** Defaults to [true].

             Set this to [false] when the module that is made is not exposed in an mli.
             Registering a pretty printer without exposing it causes an error in utop. *)
    -> module_name:string
    -> include_default_validation:bool
         (** If [true], [of_string] will raise if passed a string that is empty or has
             whitespace on either edge. *)
    -> unit
    -> ((module S_with_extras)[@mode local] [@modality p])
  [@@modality p = (nonportable, portable)]
end
