open Std_internal

(* The tests generated by the functor are described in [stable_unit_test_intf.ml].
   The tests are run like any other unit tests: by the inline test runner when the functor
   is applied. *)
module Make (T : Stable_unit_test_intf.Arg) : sig end
