open Std_internal

(* The tests generated by these functors are run like any other unit tests: by the inline
   test runner when the functor is applied. *)

(* See [stable_unit_test_intf.ml] for documentation. *)
module Make (T : Stable_unit_test_intf.Arg) : sig end

(* See [stable_unit_test_intf.ml] for documentation. *)
module Make_unordered_container (T : Stable_unit_test_intf.Unordered_container_arg)
  : sig end
